apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.geth.name }}-replica-deployment
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  replicas: {{ .Values.geth.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.geth.name }}-replica
  template:
    metadata:
      labels:
        app: {{ .Values.geth.name }}-replica
    spec:
      containers:
        - name: {{ .Values.geth.name }}-replica
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 7300
          volumeMounts:
            - name: bin-data
              mountPath: /app/data/bin
            - name: datadir
              mountPath: /app/data/datadir
            - name: configurations
              mountPath: /app/data/configurations
          envFrom:
            - configMapRef:
                name: {{ .Values.geth.name }}-replica-env
      volumes:
        - name: bin-data
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-replica-pvc-bin
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-replica-pvc-datadir
        - name: configurations
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-replica-pvc-configurations
