apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.geth.name }}-replica-deployment
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.geth.name }}-replica
  template:
    metadata:
      labels:
        app: {{ .Values.geth.name }}-replica
    spec:
      containers:
        - name: {{ .Values.geth.name }}-replica
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: [ "/usr/local/bin/geth" ]
          args: 
            - "--datadir=/app/data/datadir"
            - "--verbosity=3"
            - "--networkid={{ .Values.chain.id }}"
            - "--syncmode=full"
            - "--gcmode=full" # replicas use full instead of archive
            - "--nodiscover"
            - "--maxpeers=0" # defaults 0 maybe remove
            - "--port=30313" # different from optimism's default, 30303
            - "--rpc.allow-unprotected-txs"  # allow legacy transactions for deterministic deployment
            - "--http"
            - "--http.corsdomain=*"
            - "--http.vhosts=*"
            - "--http.addr=0.0.0.0"
            - "--http.port=8545" # different from optimism's default, 9545
            - "--http.api=web3,debug,eth,txpool,net,engine"
            - "--ws"
            - "--ws.addr=0.0.0.0"
            - "--ws.port=8546"
            - "--ws.origins=*"
            - "--ws.api=debug,eth,txpool,net,engine"
            - "--authrpc.addr=0.0.0.0"
            - "--authrpc.port=9551"
            - "--authrpc.vhosts=*"
            - "--authrpc.jwtsecret=/app/data/configurations/jwt-secret.json"
            {{- if .Values.monitoring.enabled }}
            - "--metrics" # defaults localhost:7300
            {{- end }}
            - "--rollup.disabletxpoolgossip=True"
            - "--history.transactions=2350000"
            - "--state.scheme=hash"  # TODO: investigate why state.scheme=path is not working
          ports:
            - containerPort: 8545
            - containerPort: 8546
            - containerPort: 9551
            - containerPort: 7300
          volumeMounts:
            - name: datadir
              mountPath: /app/data/datadir
            - name: configurations
              mountPath: /app/data/configurations
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-replica-pvc-datadir
        - name: configurations
          persistentVolumeClaim:
            claimName: configurations-pvc