apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geth.name }}-replica-service
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.geth.name }}-replica
  ports:
    - name: rpc
      port: 9545
      targetPort: 9545
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: 8546
      protocol: TCP
    - name: rpc-auth
      port: 9551
      targetPort: 9551
    - name: metrics
      port: 7300
      targetPort: 7300