/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_APP_REGION: string
  readonly VITE_IS_TESTNET: string
  readonly VITE_MARKETPLACE_ADDRESS: string
  readonly VITE_ERC20_TOKEN_ADDRESS: string
  readonly VITE_ERC20_TOKEN_SYMBOL: string
  readonly VITE_MARKETPLACE_CHAIN_ID: string
  readonly VITE_MARKETPLACE_SEQUENCER_OFFERS: string
  readonly VITE_MARKETPLACE_REPLICA_OFFERS: string
  readonly VITE_PROVIDER_NAME: string
  readonly VITE_PINATA_JWT: string
  readonly VITE_GATEWAY_URL: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}