apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.node.name }}-sequencer-deployment
  labels:
    app: {{ .Values.node.name }}-sequencer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.node.name }}-sequencer
  template:
    metadata:
      labels:
        app: {{ .Values.node.name }}-sequencer
    spec:
      containers:
        - name: {{ .Values.node.name }}-sequencer
          image: {{ .Values.node.image.repository }}:{{ .Values.node.image.tag }}
          ports:
            - name: http
              containerPort: 8547
            - name: p2p
              containerPort: 9221
          envFrom:
            - configMapRef:
                name: {{ .Values.node.name }}-sequencer-env
          volumeMounts:
            - name: bin-data
              mountPath: /app/data/bin
            - name: configurations
              mountPath: /app/data/configurations
          readinessProbe:
            httpGet:
              path: /health
              port: rpc
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: rpc
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: bin-data
          persistentVolumeClaim:
            claimName: {{ .Values.node.name }}-sequencer-pvc-bin
        - name: configurations
          persistentVolumeClaim:
            claimName: {{ .Values.node.name }}-sequencer-pvc-configurations