{
 "title": "Geth Overview",
 "description": "A Prometheus metric dashboard for go-ethereum, supports all blockchains compatible with go-ethereum",
 "tags": [
  "go-ethereum",
  "blockchain",
  "ethereum",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "chain",
    "label": "chain",
    "query": {
     "query": "label_values(chain_head_block{}, chain)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(chain_head_block{chain=~\"$chain\"}, instance)"
    }
   },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   }
  ]
 },
 "panels": [
  {
   "title": "Blockchain",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latest header",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_header{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain head",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "chain_head_header{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Chain Reorg Add",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_add{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_pending{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "txpool_pending{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_receipt{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Local transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_local{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Chain Reorg Drop",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_reorg_drop{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latest block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chain_head_block{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "txpool_queued{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Block processing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "chain_execution{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "storage commit (q=$quantile)"
    },
    {
     "expr": "chain_snapshot_commits{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}",
     "legendFormat": "snapshot commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(txpool_valid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    },
    {
     "expr": "rate(txpool_known{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "known"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Success RPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(geth_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (chain, instance, method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failure RPC QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(geth_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (chain, instance, method)",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "Success RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(geth_rpc_requests_success{quantile='$quantile', instance=\"$instance\"}[5m])) by (chain, instance, method) \n/ \nsum(rate(geth_rpc_requests_success_count{instance=\"$instance\"}[5m])) by (chain, instance, method) /1e6 \n< 1e200",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Failure RPC Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "sum(rate(geth_rpc_requests_failure{quantile='$quantile', instance=\"$instance\"}[5m])) by (chain, instance, method) / sum(rate(geth_rpc_requests_failure_count{instance=\"$instance\"}[5m])) by (chain, instance, method) /1e6",
     "legendFormat": "{{method}}"
    },
    {}
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(system_cpu_sysload{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "system"
    },
    {
     "expr": "avg(system_cpu_syswait{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "iowait"
    },
    {
     "expr": "avg(system_cpu_procload{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "geth"
    },
    {
     "expr": "avg(system_cpu_goroutines{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "goroutines"
    },
    {
     "expr": "avg(system_cpu_threads{chain=\"$chain\", instance=~\"$instance\"}) by (instance)",
     "legendFormat": "threads"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(system_memory_allocs{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "held"
    },
    {
     "expr": "rate(system_memory_frees{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(p2p_ingress{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ingress-rate"
    },
    {
     "expr": "rate(p2p_egress{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "egress-rate"
    },
    {
     "expr": "p2p_ingress{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "igress-flow"
    },
    {
     "expr": "p2p_egress{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "egress-flow"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "p2p_peers{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "dials"
    },
    {
     "expr": "rate(p2p_serves{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "serves"
    }
   ]
  },
  {
   "title": "Downloader",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Throttle",
   "type": "stat",
   "description": "Measured in #peers per second",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(eth_downloader_throttle{chain=\"$chain\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_downloader_bodies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "bodies in"
    },
    {
     "expr": "rate(eth_downloader_headers_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "headers in"
    },
    {
     "expr": "rate(eth_downloader_receipts_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "receipts in"
    }
   ]
  },
  {
   "title": "Abnormal QPS",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "eth_downloader_bodies_drop{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "bodies drop"
    },
    {
     "expr": "eth_downloader_headers_drop{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "headers drop"
    },
    {
     "expr": "eth_downloader_receipts_drop{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "receipts drop"
    },
    {
     "expr": "eth_downloader_bodies_timeout{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "bodies timeout"
    },
    {
     "expr": "eth_downloader_headers_timeout{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "headers timeout"
    },
    {
     "expr": "eth_downloader_receipts_timeout{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "receipts timeout"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(eth_downloader_bodies_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "bodies(q={{quantile}})"
    },
    {
     "expr": "rate(eth_downloader_headers_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "headers(q={{quantile}})"
    },
    {
     "expr": "rate(eth_downloader_receipts_req{chain=\"$chain\", instance=~\"$instance\", quantile=\"$quantile\"}[1m])",
     "legendFormat": "receipts(q={{quantile}})"
    }
   ]
  },
  {
   "title": "Fetcher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Waiting Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_waiting_peers{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Waiting Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_waiting_hashes{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queueing Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_queueing_peers{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queueing Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_queueing_hashes{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fetching Peers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_fetching_peers{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fetching Hashes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eth_fetcher_transaction_fetching_hashes{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "QPS of Transaction",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_fetcher_transaction_request_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "request out"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_fail{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "request fail"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_done{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "request done"
    },
    {
     "expr": "rate(eth_fetcher_transaction_request_timeout{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "request timeout"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "replies in"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_known{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "replies known"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_underpriced{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "replies underpriced"
    },
    {
     "expr": "rate(eth_fetcher_transaction_replies_otherreject{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "replies otherreject"
    }
   ]
  },
  {
   "title": "QPS of Block",
   "type": "timeseries",
   "description": "Measured in blocks per second",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(eth_fetcher_block_bodies{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "bodies"
    },
    {
     "expr": "rate(eth_fetcher_block_headers{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "headers"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_headers_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "filter headers in"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_headers_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "filter headers out"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_bodies_in{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "filter bodies in"
    },
    {
     "expr": "rate(eth_fetcher_block_filter_bodies_out{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "filter bodies out"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ethdb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ethdb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "ancient write"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_input{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "compact read"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_output{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "compact write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_read{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "eth_db_chaindata_disk_write{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "eth_db_chaindata_ancient_read{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient read"
    },
    {
     "expr": "eth_db_chaindata_ancient_write{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_disk_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "leveldb"
    },
    {
     "expr": "eth_db_chaindata_ancient_size{chain=\"$chain\", instance=~\"$instance\"}",
     "legendFormat": "ancient"
    }
   ]
  },
  {
   "title": "Compact Writedelay Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_counter{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Compact",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_compact_time{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_nonlevel0{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "level0"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_level0{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "~level0"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_memory{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "mem"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_seek{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "seek"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_duration{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delay time"
    },
    {
     "expr": "rate(eth_db_chaindata_compact_writedelay_counter{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delay count"
    }
   ]
  },
  {
   "title": "Compact Writedelay Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "eth_db_chaindata_compact_writedelay_duration{chain=\"$chain\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Trie Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Clean cache-BPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(trie_memcache_clean_write{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Dirty cache-BPS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "commit"
    }
   ]
  },
  {
   "title": "Clean cache-Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/(rate(trie_memcache_clean_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])+rate(trie_memcache_clean_hit{chain=\"$chain\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "Dirty cache-Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_dirty_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "miss"
    },
    {
     "expr": "rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m])/(rate(trie_memcache_dirty_miss{chain=\"$chain\", instance=~\"$instance\"}[1m])+rate(trie_memcache_dirty_hit{chain=\"$chain\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "hit rate"
    }
   ]
  },
  {
   "title": "MPT-Nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_commit_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(trie_memcache_flush_nodes{chain=\"$chain\", instance=~\"$instance\"}[1m])",
     "legendFormat": "overflow"
    }
   ]
  },
  {
   "title": "MPT-Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_commit_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(trie_memcache_flush_time{chain=\"$chain\", instance=~\"$instance\", quantile=~\"$quantile\"}[1m])",
     "legendFormat": "overflow"
    }
   ]
  }
 ]
}