apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"  # Set as default
provisioner: docker.io/hostpath
reclaimPolicy: Delete
volumeBindingMode: Immediate