apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.demo.deployment.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.demo.deployment.appLabel }}
    spec:
      containers:
      - name: proxyd
        image: "{{ .Values.proxyd.image.repository }}:{{ .Values.proxyd.image.tag }}"
        imagePullPolicy: {{ .Values.proxyd.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxyd.service.port }}
        volumeMounts:
        - name: proxyd-config-volume
          mountPath: /etc/proxyd
        command: ["/bin/entrypoint.sh"]
        args: ["/bin/proxyd", "/etc/proxyd/proxyd.toml"]
      volumes:
      - name: proxyd-config-volume
        configMap:
          name: proxyd-config
