apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.geth.name }}-sequencer-configuration-job
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.geth.name }}-sequencer
    spec:
      restartPolicy: OnFailure
      containers:
        - name: unzip-artifacts
          image: busybox:1.36.1
          command:
            - sh
            - "-c"
            - |
              echo "Decoding and unzipping artifacts..."
              unzip config/artifacts.zip -d /app/data/configurations
          volumeMounts:
            - name: read-config-volume
              mountPath: /config
            - name: write-config-volume
              mountPath: /app/data/configurations
      volumes:
        - name: read-config-volume
          configMap:
            name: core-config-files
        - name: write-config-volume
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-sequencer-pvc-configurations
