apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.geth.name }}-sequencer-deployment
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.geth.name }}-sequencer
  template:
    metadata:
      labels:
        app: {{ .Values.geth.name }}-sequencer
    spec:
      containers:
        - name: {{ .Values.geth.name }}-sequencer
          image: {{ .Values.geth.image.repository }}:{{ .Values.geth.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: [ "sh", "/app/data/scripts/entrypoint.sh" ]
          ports:
            - containerPort: {{ .Values.geth.ports.rpc }}
            - containerPort: {{ .Values.geth.ports.ws }}
            - containerPort: {{ .Values.geth.ports.rpcAuth }}
            - containerPort: {{ .Values.geth.ports.metrics }}
          volumeMounts:
            - name: datadir
              mountPath: /app/data/datadir
            - name: configurations
              mountPath: /app/data/configurations
            - name: configuration-scripts
              mountPath: /app/data/scripts
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-sequencer-pvc-datadir
        - name: configurations
          persistentVolumeClaim:
            claimName: {{ .Values.geth.name }}-sequencer-pvc-configurations
        - name: configuration-scripts
          configMap:
            name: geth-sequencer-scripts