{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.geth.name }}-sequencer-monitor
spec:
  selector:
    matchLabels:
      app: {{ .Values.geth.name }}-sequencer
  endpoints:
  - port: metrics
{{- end }}