apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-sequencer-pvc-datadir
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi # 4Ti optimal
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-sequencer-pvc-configurations
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: gp2
