apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-sequencer-pvc-datadir
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if ne .Values.global.storageClassName "" }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-sequencer-pvc-configurations
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  # storageClassName: gp2
