apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-sequencer-pvc-datadir
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
  storageClassName: gp2

