apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    cert-manager.io/issuer: "letsencrypt"  # TLS requirement - enables cert-manager
spec:
  ingressClassName: nginx
  {{- if ne .Values.domain.host "localhost" }}
  tls:
    - hosts:
        - {{ .Values.domain.host }}
      secretName: {{ .Values.domain.host | replace "." "-" }}-tls  # TLS requirement - certificate stored here
  {{- end }}
  rules:
    - host: {{ .Values.domain.host }}
      http:
        paths:
          - path: {{ .Values.proxyd.ingress.nodePath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.proxyd.name }}-service
                port:
                  number: {{ .Values.proxyd.service.port }}