apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.node.name }}-replica-pvc-bin
  labels:
    app: {{ .Values.node.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.node.name }}-replica-pvc-configurations
  labels:
    app: {{ .Values.node.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
