apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.node.name }}-replica-service
  labels:
    app: {{ .Values.node.name }}-replica
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.node.name }}-replica
  ports:
    - name: http
      port: 8547
      targetPort: 8547
    - name: p2p-tcp
      port: 9221
      targetPort: 9221
      protocol: TCP
    - name: p2p-udp
      port: 9221
      targetPort: 9221
      protocol: UDP
    - name: metrics
      port: 7300
      targetPort: 7300