apiVersion: v1
kind: ConfigMap
metadata:
  name: op-geth-dashboard
  labels:
    grafana_dashboard: "1"
data:
    {{- $file := .Files.Get "dashboards/op-geth.json" }}
  op-geth.json: |-
    {{ $file | nindent 6 }}
  