/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DeploymentsIdImport } from './routes/deployments/$id'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthSigninImport } from './routes/auth/signin'
import { Route as AuthConfirmImport } from './routes/auth/confirm'
import { Route as CreateVerifyIndexImport } from './routes/create/verify/index'
import { Route as CreateSetupIndexImport } from './routes/create/setup/index'
import { Route as CreateDeployIndexImport } from './routes/create/deploy/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DeploymentsIdRoute = DeploymentsIdImport.update({
  id: '/deployments/$id',
  path: '/deployments/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthConfirmRoute = AuthConfirmImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRoute,
} as any)

const CreateVerifyIndexRoute = CreateVerifyIndexImport.update({
  id: '/create/verify/',
  path: '/create/verify/',
  getParentRoute: () => rootRoute,
} as any)

const CreateSetupIndexRoute = CreateSetupIndexImport.update({
  id: '/create/setup/',
  path: '/create/setup/',
  getParentRoute: () => rootRoute,
} as any)

const CreateDeployIndexRoute = CreateDeployIndexImport.update({
  id: '/create/deploy/',
  path: '/create/deploy/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthSigninRoute = AuthSigninImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRoute,
} as any)

const AuthConfirmRoute = AuthConfirmImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmImport
      parentRoute: typeof rootRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/deployments/$id': {
      id: '/deployments/$id'
      path: '/deployments/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof DeploymentsIdImport
      parentRoute: typeof rootRoute
    }
    '/create/deploy/': {
      id: '/create/deploy/'
      path: '/create/deploy'
      fullPath: '/create/deploy'
      preLoaderRoute: typeof CreateDeployIndexImport
      parentRoute: typeof rootRoute
    }
    '/create/setup/': {
      id: '/create/setup/'
      path: '/create/setup'
      fullPath: '/create/setup'
      preLoaderRoute: typeof CreateSetupIndexImport
      parentRoute: typeof rootRoute
    }
    '/create/verify/': {
      id: '/create/verify/'
      path: '/create/verify'
      fullPath: '/create/verify'
      preLoaderRoute: typeof CreateVerifyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/create/deploy': typeof CreateDeployIndexRoute
  '/create/setup': typeof CreateSetupIndexRoute
  '/create/verify': typeof CreateVerifyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/create/deploy': typeof CreateDeployIndexRoute
  '/create/setup': typeof CreateSetupIndexRoute
  '/create/verify': typeof CreateVerifyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/deployments/$id': typeof DeploymentsIdRoute
  '/create/deploy/': typeof CreateDeployIndexRoute
  '/create/setup/': typeof CreateSetupIndexRoute
  '/create/verify/': typeof CreateVerifyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/confirm'
    | '/auth/signin'
    | '/auth/signup'
    | '/deployments/$id'
    | '/create/deploy'
    | '/create/setup'
    | '/create/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/confirm'
    | '/auth/signin'
    | '/auth/signup'
    | '/deployments/$id'
    | '/create/deploy'
    | '/create/setup'
    | '/create/verify'
  id:
    | '__root__'
    | '/'
    | '/auth/confirm'
    | '/auth/signin'
    | '/auth/signup'
    | '/deployments/$id'
    | '/create/deploy/'
    | '/create/setup/'
    | '/create/verify/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  CreateDeployIndexRoute: typeof CreateDeployIndexRoute
  CreateSetupIndexRoute: typeof CreateSetupIndexRoute
  CreateVerifyIndexRoute: typeof CreateVerifyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  DeploymentsIdRoute: DeploymentsIdRoute,
  CreateDeployIndexRoute: CreateDeployIndexRoute,
  CreateSetupIndexRoute: CreateSetupIndexRoute,
  CreateVerifyIndexRoute: CreateVerifyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/confirm",
        "/auth/signin",
        "/auth/signup",
        "/deployments/$id",
        "/create/deploy/",
        "/create/setup/",
        "/create/verify/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/confirm": {
      "filePath": "auth/confirm.tsx"
    },
    "/auth/signin": {
      "filePath": "auth/signin.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/deployments/$id": {
      "filePath": "deployments/$id.tsx"
    },
    "/create/deploy/": {
      "filePath": "create/deploy/index.tsx"
    },
    "/create/setup/": {
      "filePath": "create/setup/index.tsx"
    },
    "/create/verify/": {
      "filePath": "create/verify/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
