apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proposer.name }}-deployment
  labels:
    app: {{ .Values.proposer.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.proposer.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.proposer.name }}
    spec:
      containers:
        - name: {{ .Values.proposer.name }}
          image: {{ .Values.proposer.image.repository }}:{{ .Values.proposer.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: [ "/usr/local/bin/op-proposer" ]
          args:
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-proposer/flags/flags.go
            - "--l1-eth-rpc={{ .Values.chain.l1Rpc }}"
            - "--rollup-rpc=http://{{ .Values.node.name }}-sequencer-service:7545"
            - "--poll-interval=1s"
            - "--l2oo-address={{- $addresses := .Files.Get .Values.configFile.addresses | fromJson }}{{- required "L2OutputOracleProxy is required" (index $addresses "L2OutputOracleProxy") }}"
            - "--allow-non-finalized"
            # RPC Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/rpc/cli.go
            - "--rpc.addr=0.0.0.0"
            - "--rpc.port=5545" # different from optimism's default, 8560
            # Tx Manager Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/txmgr/cli.go
            - "--num-confirmations=1"
            - "--private-key={{ .Values.proposer.config.privateKey }}"
            # Metrics Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/metrics/cli.go
            {{- if .Values.monitoring.enabled }}
            - "--metrics.enabled"
            {{- end }}
          ports:
            - containerPort: 5545 
            - containerPort: 7300
