apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.proposer.name }}-monitor
spec:
  selector:
    matchLabels:
      app: {{ .Values.proposer.name }}
  endpoints:
  - port: metrics