apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.proposer.name }}-pvc-bin
  labels:
    app: {{ .Values.proposer.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.proposer.name }}-pvc-deployments
  labels:
    app: {{ .Values.proposer.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
