apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proposer.name }}-service
  labels:
    app: {{ .Values.proposer.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.proposer.name }}
  ports:
    - name: http
      port: 5545
      targetPort: 5545
    - name: metrics
      port: 7300
      targetPort: 7300

