apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.node.name }}-sequencer-service
  labels:
    app: {{ .Values.node.name }}-sequencer
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.node.name }}-sequencer
  ports:
    - name: rpc
      port: {{ .Values.node.ports.rpc }}
      targetPort: {{ .Values.node.ports.rpc }}
    - name: p2p-tcp
      port: {{ .Values.node.ports.p2p }}
      targetPort: {{ .Values.node.ports.p2p }}
      protocol: TCP
    - name: p2p-udp
      port: {{ .Values.node.ports.p2p }}
      targetPort: {{ .Values.node.ports.p2p }}
      protocol: UDP
    - name: metrics
      port: {{ .Values.node.ports.metrics }}
      targetPort: {{ .Values.node.ports.metrics }}