{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: blockscout-postgres-secret
  labels:
    app: blockscout-postgres
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.blockscout-stack.postgres.dbName }}
  POSTGRES_USER: {{ .Values.blockscout-stack.postgres.user }}
  POSTGRES_PASSWORD: {{ .Values.blockscout-stack.postgres.password }}
{{- end }}