{{- if .Values.explorer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockscout-postgres-deployment
  labels:
    app: blockscout-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockscout-postgres
  template:
    metadata:
      labels:
        app: blockscout-postgres
    spec:
      containers:
      - name: db
        image: "{{ .Values.blockscoutStack.postgres.image.repository }}:{{ .Values.blockscoutStack.postgres.image.tag }}"
        envFrom:
          - secretRef:
              name: blockscout-postgres-secret
        env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: blockscout-postgres-pvc
{{- end }}