domain:
  host: localhost # demo.example.com
  email: email@email.com

global:
  image:
    pullPolicy: IfNotPresent

demo:
  ingress:
    path: /
  deployment:
    name: demo-deployment
    appLabel: demo-app
    replicaCount: 1
    containerPort: 80
    containerName: demo
    image:
      repository: nginx
      tag: latest
  service:
    name: demo-service
    port: 80
    targetPort: 80

proxyd:
  name: proxyd
  image:
    repository: wakeuplabs/proxyd
    tag: latest
  service:
    port: 8080
    targetPort: 8080
  config:
    rpc_url_alchemy: ""
    ws_url_alchemy: ""
    alchemy_username: ""
    alchemy_password: ""

redis:
  name: proxyd-redis
  image:
    repository: redis
    tag: latest

explorer:
  enabled: false

monitoring:
  enabled: true

kube-prometheus-stack:
  grafana:
    service:
      port: 90
  prometheus:
    serviceAccount:
      name: "" # prometheus
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false # Workaround for Error: path / is mounted on / but it is not a shared or slave mount
      mountPropagation: HostToContainer

geth:
  name: op-geth
  deployment:
    replicaCount: 2
  image:
    repository: wakeuplabs/op-geth
    tag: latest

node:
  name: op-node
  image:
    repository: wakeuplabs/op-node
    tag: latest

batcher:
  name: op-batcher
  image:
    repository: wakeuplabs/op-batcher
    tag: latest

proposer:
  name: op-proposer
  image:
    repository: wakeuplabs/op-proposer
    tag: latest
