domain:
  host: localhost # demo.example.com
  email: email@email.com
chain:
  id: "11155420"
global:
  image:
    pullPolicy: IfNotPresent
  l1:
    rpc: "https://eth-sepolia.g.alchemy.com/v2/5600JheK0TTROlJ6O0wrc0gF3W9wIqm8/"
configFile:
  rollup: "config/rollup.json"
  jwtSecret: "config/jwt-secret.txt"
  nodeP2PPriv: "config/opnode_p2p_priv.txt"
  addresses: "config/addresses.json"
  genesis: "config/genesis-l2.json"
  
demo:
  ingress:
    path: /demo
  deployment:
    name: demo-deployment
    appLabel: demo-app
    replicaCount: 1
    containerPort: 80
    containerName: demo
    image:
      repository: nginx
      tag: latest
  service:
    name: demo-service
    port: 80
    targetPort: 80

geth:
  name: op-geth
  deployment:
    replicaCount: 2
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    tag: v1.101408.0

node:
  name: op-node
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-node
    tag: v1.3.1
  config:
    p2p:
      enabled: false
      sequencerKey: ""

batcher:
  name: op-batcher
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher
    tag: v1.9.4
  config:
    batcherKey: ""
    mnemonic: ""
    hdPath: ""
    p2p:
      sequencerAccount: ""

proposer:
  name: op-proposer
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer
    tag: v1.9.4
  config:
    proposerKey: ""
    mnemonic: ""
    hdPath: ""

proxyd:
  name: proxyd
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/proxyd
    tag: latest
  service:
    port: 8080
    targetPort: 8080
  ingress:
    path: /proxyd
  config:
    rpc_url_alchemy: "https://opt-sepolia.g.alchemy.com/v2/5600JheK0TTROlJ6O0wrc0gF3W9wIqm8"
    ws_url_alchemy: "wss://opt-sepolia.g.alchemy.com/v2/5600JheK0TTROlJ6O0wrc0gF3W9wIqm8"

redis:
  name: proxyd-redis
  image:
    repository: redis
    tag: latest

explorer:
  enabled: true

monitoring:
  enabled: true

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      paths: 
        - /grafana
      hosts:
        - "localhost"
  prometheus:
    serviceAccount:
      name: "" # prometheus
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false # Workaround for Error: path / is mounted on / but it is not a shared or slave mount
      mountPropagation: HostToContainer

blockscout-stack:
  blockscout:
    extraEnv:
      - name: ECTO_USE_SSL
        value: "false"
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: blockscout-secret
            key: DATABASE_URL
  frontend:
    ingress:
      enabled: true
      className: nginx
      paths: 
        - path: /explorer
      hostname: localhost
    extraEnv:
      - name: NEXT_PUBLIC_APP_HOST
        value: localhost
      - name: NEXT_PUBLIC_API_HOST
        value: localhost

blockscout:
  postgres:
    dbName: blockscout
    user: userShouldBeSet
    password: passwordShouldBeSet
    image:
      repository: postgres
      tag: latest
