domain:
  host: localhost # demo.example.com
  email: email@email.com

global:
  image:
    pullPolicy: IfNotPresent

chain:
  id: 10 # figure out how to take it from files, but files are ziped
  l1Rpc: "<L1 eth RPC URL>"
  artifacts: "config/artifacts.zip"
  addresses: "config/addresses.json"

geth:
  name: op-geth
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth
    tag: v1.101315.3
  deployment:
    replicaCount: 1
  ports:
    rpc: 8545 # != optimism docs: 9545 
    ws: 8546 # != optimisms docs: 9546
    rpcAuth: 9551
    metrics: 7300

node:
  name: op-node
  image:
    repository: matzapata/op-node
    tag: latest
  config:
    p2pEnabled: false
  ports:
    rpc: 7545 # != optimism docs: 8547
    p2p: 9222
    metrics: 7300

batcher:
  name: op-batcher
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-batcher
    tag: v1.9.4
  config:
    privateKey: ""
  ports:
    rpc: 6545 # != optimism docs: 8548
    metrics: 7300

proposer:
  name: op-proposer
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-proposer
    tag: v1.9.4
  config:
    privateKey: ""
  ports:
    rpc: 5545 # != optimism docs: 8560
    metrics: 7300

proxyd:
  name: proxyd
  image:
    repository: us-docker.pkg.dev/oplabs-tools-artifacts/images/proxyd
    tag: latest
  service:
    port: 8080
    targetPort: 8080
  ingress:
    nodePath: /rpc
  config:
    rpc_url_alchemy: "https://opt-sepolia.g.alchemy.com/v2/..."
    ws_url_alchemy: "wss://opt-sepolia.g.alchemy.com/v2/..."
  redis:
    name: proxyd-redis
    image:
      repository: redis
      tag: latest

explorer:
  enabled: false

monitoring:
  enabled: false

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      paths: 
        - /grafana
      hosts:
        - "localhost"
  prometheus:
    serviceAccount:
      name: "" # prometheus
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false # Workaround for Error: path / is mounted on / but it is not a shared or slave mount
      mountPropagation: HostToContainer

blockscoutStack:
  blockscout:
    extraEnv:
      - name: ECTO_USE_SSL
        value: "false"
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: blockscout-secret
            key: DATABASE_URL
      - name: RPC_ADDR
        value: "http://op-node-replica-service"
      - name: RPC_PORT
        value: 7545
    
  frontend:
    ingress:
      enabled: true
      className: nginx
      paths: 
        - path: /explorer
      hostname: localhost
    extraEnv:
      - name: NEXT_PUBLIC_APP_HOST
        value: localhost
      - name: NEXT_PUBLIC_API_HOST
        value: localhost

  postgres:
    dbName: blockscout
    user: blockscout-db-user
    password: blockscout-db-password
    image:
      repository: postgres
      tag: latest
