domain:
  host: localhost # demo.example.com
  email: email@email.com

global:
  image:
    pullPolicy: IfNotPresent

demo:
  ingress:
    path: /demo
  deployment:
    name: demo-deployment
    appLabel: demo-app
    replicaCount: 1
    containerPort: 80
    containerName: demo
    image:
      repository: nginx
      tag: latest
  service:
    name: demo-service
    port: 80
    targetPort: 80

geth:
  name: op-geth
  deployment:
    replicaCount: 2
  image:
    repository: wakeuplabs/op-geth
    tag: latest

node:
  name: op-node
  image:
    repository: wakeuplabs/op-node
    tag: latest

batcher:
  name: op-batcher
  image:
    repository: wakeuplabs/op-batcher
    tag: latest

proposer:
  name: op-proposer
  image:
    repository: wakeuplabs/op-proposer
    tag: latest

proxyd:
  name: proxyd
  image:
    repository: wakeuplabs/proxyd
    tag: latest
  service:
    port: 8080
    targetPort: 8080
  ingress:
    path: /proxyd
  config:
    rpc_url_alchemy: "https://opt-sepolia.g.alchemy.com/v2/5600JheK0TTROlJ6O0wrc0gF3W9wIqm8"
    ws_url_alchemy: "wss://opt-sepolia.g.alchemy.com/v2/5600JheK0TTROlJ6O0wrc0gF3W9wIqm8"

redis:
  name: proxyd-redis
  image:
    repository: redis
    tag: latest

explorer:
  enabled: true

monitoring:
  enabled: true

kube-prometheus-stack:
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      paths: 
        - /grafana
      hosts:
        - "localhost"
  prometheus:
    serviceAccount:
      name: "" # prometheus
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: false # Workaround for Error: path / is mounted on / but it is not a shared or slave mount
      mountPropagation: HostToContainer

blockscout-stack:
  blockscout:
    extraEnv:
      - name: ECTO_USE_SSL
        value: "false"
      - name: DATABASE_URL
        valueFrom:
          secretKeyRef:
            name: blockscout-secret
            key: DATABASE_URL
  frontend:
    ingress:
      enabled: true
      className: nginx
      paths: 
        - path: /explorer
      hostname: localhost
    extraEnv:
      - name: NEXT_PUBLIC_APP_HOST
        value: localhost
      - name: NEXT_PUBLIC_API_HOST
        value: localhost

blockscout:
  postgres:
    dbName: blockscout
    user: userShouldBeSet
    password: passwordShouldBeSet
    image:
      repository: postgres
      tag: latest
