apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config-files
  labels:
    app: configurations
binaryData:
  artifacts.zip: artifacts.zip: {{ .Files.Get (required "configFile.artifacts is required" .Values.configFile.artifacts) | b64enc }}