apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: configurations-pvc
  labels:
    app: configurations
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: gp2 # efs-sc
