apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config-files
  labels:
    app: configurations
binaryData:
  artifacts.zip: {{ .Files.Get (required "configFile.artifacts is required" "config/artifacts.zip") | b64enc }}