apiVersion: apps/v1
kind: Deployment
metadata:
  name: configuration-deployment
  labels:
    app: configurations
spec:
  selector:
    matchLabels:
      app: configurations
  template:
    metadata:
      labels:
        app: configurations
    spec:
      containers:
        - name: unzip-artifacts
          image: busybox:1.36.1
          command:
            - sh
            - "-c"
            - |
              ls config
              echo "Decoding and unzipping artifacts..."
              unzip config/artifacts.zip -d /app/data/configurations
              echo "Unzipped files:"
              ls /app/data/configurations
          volumeMounts:
            - name: read-config-volume
              mountPath: /config
            - name: write-config-volume
              mountPath: /app/data/configurations
      volumes:
        - name: read-config-volume
          configMap:
            name: core-config-files
        - name: write-config-volume
          persistentVolumeClaim:
            claimName: configurations-pvc
