/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "opruaas-console-api": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "opruaas-console-artifacts": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "opruaas-console-db": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "reader": string
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "opruaas-console-ui": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "opruaas-console-vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}