apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.batcher.name }}-deployment
  labels:
    app: {{ .Values.batcher.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.batcher.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.batcher.name }}
    spec:
      containers:
        - name: {{ .Values.batcher.name }}
          image: {{ .Values.batcher.image.repository }}:{{ .Values.batcher.image.tag }} 
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: [ "/usr/local/bin/op-batcher" ]
          args:
            # Batcher-Specific Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-batcher/flags/flags.go
            - "--l1-eth-rpc={{ .Values.chain.l1Rpc }}"
            - "--l2-eth-rpc=http://{{ .Values.geth.name }}-sequencer-service:{{ .Values.geth.ports.rpc }}"
            - "--rollup-rpc=http://{{ .Values.node.name }}-sequencer-service:{{ .Values.node.ports.rpc }}"
            - "--poll-interval=1s"
            - "--sub-safety-margin=4"
            - "--max-channel-duration=1"
            # Tx Manager Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/txmgr/cli.go
            - "--num-confirmations=1"
            - "--private-key={{ .Values.batcher.config.privateKey }}"
            # Metrics Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/metrics/cli.go
            {{- if .Values.monitoring.enabled }}
            - "--metrics.enabled"
            - "--metrics.port={{ .Values.batcher.ports.metrics }}"
            {{- end }}
            # RPC Options
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-batcher/rpc/config.go
            # https://github.com/ethereum-optimism/optimism/blob/develop/op-service/rpc/cli.go
            {{- if .Values.batcher.config.enableAdmin }}
            - "--rpc.enable-admin"
            {{- end }}
            - "--rpc.addr=0.0.0.0"
            - "--rpc.port={{ .Values.batcher.ports.rpc }}" 
          ports:
            - containerPort: {{ .Values.batcher.ports.rpc }}
            - containerPort: {{ .Values.batcher.ports.metrics }}
