apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.batcher.name }}-deployment
  labels:
    app: {{ .Values.batcher.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.batcher.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.batcher.name }}
    spec:
      containers:
        - name: {{ .Values.batcher.name }}
          image: {{ .Values.batcher.image.repository }}:{{ .Values.batcher.image.tag }} 
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: 8548
            - containerPort: 7300
          volumeMounts:
            - name: bin-data
              mountPath: /app/data/bin
          envFrom:
            - configMapRef:
                name: {{ .Values.batcher.name }}-env
      volumes:
        - name: bin-data
          persistentVolumeClaim:
            claimName: {{ .Values.batcher.name }}-pvc
