apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.batcher.name }}-pvc
  labels:
    app: {{ .Values.batcher.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
