apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.batcher.name }}-service
  labels:
    app: {{ .Values.batcher.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.batcher.name }}
  ports:
    - name: rpc
      port: {{ .Values.batcher.ports.rpc }}
      targetPort: {{ .Values.batcher.ports.rpc }}
    - name: metrics
      port: {{ .Values.batcher.ports.metrics }}
      targetPort: {{ .Values.batcher.ports.metrics }}