apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.batcher.name }}-service
  labels:
    app: {{ .Values.batcher.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.batcher.name }}
  ports:
    - name: http
      port: 6545
      targetPort: 6545
    - name: metrics
      port: 7300
      targetPort: 7300