apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.batcher.name }}-service
  labels:
    app: {{ .Values.batcher.name }}
  annotations:
    prometheus.io/scrape: {{ .Values.monitoring.enabled | quote }}
    prometheus.io/port: {{ .Values.batcher.ports.metrics | quote }}
    prometheus.io/job: "op-batcher"
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.batcher.name }}
  ports:
    - name: rpc
      port: {{ .Values.batcher.ports.rpc }}
      targetPort: {{ .Values.batcher.ports.rpc }}