apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyd.redis.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.proxyd.redis.name }}
  ports:
    - port: {{ .Values.proxyd.redis.port }}
      targetPort: 6379