apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxyd.name }}-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.proxyd.name }}
  ports:
    - port: {{ .Values.proxyd.service.port }}
      targetPort: {{ .Values.proxyd.service.targetPort }}
