apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.node.name }}-replica-pvc-configurations
  labels:
    app: {{ .Values.node.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: gp2
