apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geth.name }}-sequencer-service
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.geth.name }}-sequencer
  ports:
    - name: rpc
      port: 8545
      targetPort: 8545
      protocol: TCP
    - name: ws
      port: 8546
      targetPort: 8546
      protocol: TCP
    - name: metrics
      port: 7300
      targetPort: 7300