apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.geth.name }}-sequencer-service
  labels:
    app: {{ .Values.geth.name }}-sequencer
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.geth.name }}-sequencer
  ports:
    - name: rpc
      port: 9545
      targetPort: 9545
      protocol: TCP
    - name: ws
      port: 9546
      targetPort: 9546
      protocol: TCP
    - name: rpc-auth
      port: 9551
      targetPort: 9551
    - name: metrics
      port: 7300
      targetPort: 7300