apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-replica-pvc-datadir
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Ti
  storageClassName: gp2