apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-replica-pvc-datadir
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.geth.storage.replica }}
  {{- if ne .Values.global.storageClassName "" }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-replica-pvc-configurations
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  {{- if ne .Values.global.storageClassName "" }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.geth.name }}-replica-pvc-bootnode
  labels:
    app: {{ .Values.geth.name }}-replica
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  {{- if ne .Values.global.storageClassName "" }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}