{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: blockscout-postgres-service
  labels:
    app: blockscout-postgres
spec:
  type: ClusterIP
  selector:
    app: blockscout-postgres
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}