{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockscout-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if ne .Values.global.storageClassName "" }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- end }}
{{- end }}