{{- if .Values.explorer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: blockscout-secret
  labels:
    app: blockscout-stack
type: Opaque
stringData:
  DATABASE_URL: ecto://{{ .Values.blockscoutStack.postgres.user }}:{{ .Values.blockscoutStack.postgres.password }}@blockscout-postgres-service:5432/{{ .Values.blockscoutStack.postgres.dbName }}
{{- end }}